### ISSUE TITLE
How to remove the expand effect on hover?

### ISSUE THREAD

**Issue by riazu** [darklow/social-share-kit#30]
Hi,

How can I remove the expand effect on hover?

Regards.

**Comment by darklow** [comment]
Use following CSS code to override hover efect:

``` css
/* For left side icons */
.ssk-sticky.ssk-left .ssk:hover { padding-left: 0; }
/* For right side */
.ssk-sticky.ssk-right .ssk:hover { padding-right: 0; }
```

Add this CSS either in your own CSS file (which is included after `social-share-kit.css`)
Or add `<style>` tags in your `<head>` section.
Or just add `!important` to CSS style if you can't control order of CSS files.
